# Generated by Django 3.2.6 on 2021-11-15 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='articleGroupScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='articleMemberScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='idolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='idolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='idolMemberImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='idolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='idolViemMemberLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='idolViewGroupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='imageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='myIdolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='myIdolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='videoRecognitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='videoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='searchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchLogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='memberComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberComments', to='main.idolmember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='idolMemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberThumbnail', models.CharField(max_length=50)),
                ('memberInfo', models.JSONField(default='{}')),
                ('memberSource', models.JSONField(default='{}')),
                ('valid', models.IntegerField(default=1)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idolMemberInfos', to='main.idolmember')),
            ],
        ),
        migrations.CreateModel(
            name='idolMemberIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.IntegerField(default=1)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberIncluded', to='main.idolgroup')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupIncluded', to='main.idolmember')),
            ],
        ),
        migrations.CreateModel(
            name='idolGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupThumbnail', models.CharField(max_length=50)),
                ('groupInfo', models.JSONField(default='{}')),
                ('groupSource', models.JSONField(default='{}')),
                ('valid', models.IntegerField(default=1)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idolGroupInfos', to='main.idolgroup')),
            ],
        ),
        migrations.CreateModel(
            name='groupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupComments', to='main.idolgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
