# Generated by Django 3.2.6 on 2021-12-05 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_alter_searchlog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searchLogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
