# Generated by Django 3.2.6 on 2021-11-20 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20211120_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdolMemberImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IdolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='')),
                ('size', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoRecognitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchLogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyIdolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myIdolMembers', to='main.idolmember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myIdolMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyIdolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myIdolGroups', to='main.idolgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myIdolGroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberComments', to='main.idolmember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdolViewGroupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idolViewGroupLogs', to='main.idolgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idolViewGroupLogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdolViemMemberLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idolViemMemberLogs', to='main.idolmember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idolViemMemberLogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdolMemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberInfo', models.JSONField(default=dict)),
                ('memberSource', models.JSONField(default=dict)),
                ('valid', models.BooleanField(default=True)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idolMemberInfos', to='main.idolmember')),
                ('memberThumbnail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idolMembers', to='main.imageresource')),
            ],
        ),
        migrations.CreateModel(
            name='IdolMemberIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberIncluded', to='main.idolgroup')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupIncluded', to='main.idolmember')),
            ],
        ),
        migrations.CreateModel(
            name='IdolGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupInfo', models.JSONField(default=dict)),
                ('groupSource', models.JSONField(default=dict)),
                ('valid', models.BooleanField(default=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idolGroupInfos', to='main.idolgroup')),
                ('groupThumbnail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idolGroups', to='main.imageresource')),
            ],
        ),
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupComments', to='main.idolgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleMemberScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleMemberScraps', to='main.idolmember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleMemberScraps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleGroupScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleGroupScraps', to='main.idolgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleGroupScraps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
