# Generated by Django 3.2.6 on 2021-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofacerecognition',
            name='location',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='videofacerecognition',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='videofacerecognitionshare',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='videoscene',
            name='location',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='videoscene',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='videosceneshare',
            name='description',
            field=models.JSONField(default=dict),
        ),
    ]
