# Generated by Django 3.2.6 on 2021-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlememberscrap",
            old_name="memberId",
            new_name="member",
        ),
        migrations.AddField(
            model_name="articlegroupscrap",
            name="title",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="articlememberscrap",
            name="title",
            field=models.TextField(default=""),
        ),
    ]
