# Generated by Django 3.1 on 2021-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlegroupscrap",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="articlememberscrap",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="myidolgroup",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="myidolmember",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
